name: server
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  DB_NAME: cap_project
  DB_USERNAME: ${{env.DB_USERNAME}}
  DB_PASSWORD: ${{env.DB_PASSWORD}}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd c21-tw-cap-group2
          git pull origin main
          yarn install
          yarn knex migrate:latest --env production
          forever restart index.js
        host: 35.168.226.161
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
